import React, { useState, useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import './ImageDisplay.css';  // Import the CSS for this component
import axios from 'axios';

const ImageComponent = () => {
    const [imageUrl, setImageUrl] = useState('');
    const [data, setData] = useState(null);
    const hasFetchedImage = useRef(false); // Add a ref to track whether the image has been fetched

    useEffect(() => {
        const fetchImage = async () => {
            try {
                const response = await axios.get('http://127.0.0.1:5000/generated-image');
                const resData = response.data;
                setData(resData);
                const generatedImageBlob = new Uint8Array(resData.image.match(/.{1,2}/g).map(byte => parseInt(byte, 16)));
                const generatedImageUrl = URL.createObjectURL(new Blob([generatedImageBlob.buffer], { type: 'image/jpeg' }));
                setImageUrl(generatedImageUrl);
            } catch (error) {
                console.error('Error fetching image:', error);
            }
        };

        if (!hasFetchedImage.current) { // Check if the image has already been fetched
            fetchImage();
            hasFetchedImage.current = true; // Set the ref to true to prevent re-fetching
        }
       
    }, []); // Empty dependency array ensures the effect only runs once
    if (!data) {
        return <div>Loading...</div>;
      }

    return (
        <div className="image-page">
            <div className="navbar">
                <Link to="/">
                    <div className="logo">Matching Models</div>
                </Link>
                <nav>
                    <ul>
                        <li><a href="#about">About</a></li>
                        <li><a href="#features">Features</a></li>
                        <li><a href="#contact">Contact</a></li>
                    </ul>
                </nav>
            </div>

            <div className="image-section">
                {imageUrl ? (
                    <img src={imageUrl} alt="Generated Image" className="displayed-image" />
                ) : (
                    <p>Loading image...</p>
                )}
            </div>
            <div >
                <p style={{fontSize: '1.2rem', margin: '10px 0'}}><strong style={{color: '#ff5722'}}>Generated By:</strong> {data.model}</p>
            </div>
            <div className="proceed-container">
                <Link to="/results">
                    <button className="proceed">View Results</button>
                </Link>
            </div>
            <div><br /></div>
            <footer className="footer-section">
                <p>&copy; 2024 Generative Tools | <a href="#contact">Contact Us</a></p>
            </footer>
        </div>
    );
};

export default ImageComponent;
